name: Docs
on: [push, pull_request]

jobs:
  build-and-deloy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        uses: lhotari/action-upterm@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]

      - name: Build docs
        run: |
          cd docs
          make html

      - name: Pull latest gh-pages
        if: "(contains(github.ref, 'main')) && github.event_name == 'push'"
        run: |
          cd ..
          git clone https://github.com/ja-thomas/pbmohpo --branch gh-pages --single-branch gh-pages

      - name: Copy new docs into gh-pages
        if: "(contains(github.ref, 'main')) && github.event_name == 'push'"
        run: |
          branch_name=${GITHUB_REF##*/}
          cd ../gh-pages
          rm -rf $branch_name
          rm -rf docs/*
          cp -r ../pbmohpo/docs/build/html $branch_name

      - name: Push to gh-pages
        if: "(contains(github.ref, 'main')) && github.event_name == 'push'"
        run: |
          last_commit=$(git log --pretty=format:"%an: %s")
          cd ../gh-pages
          branch_name=${GITHUB_REF##*/}
          mv -f $branch_name/* docs
          rm -r $branch_name
          git add docs
          git config --global user.name "Github Actions"
          git config --global user.email "not@mail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit --allow-empty -am "$last_commit"
          git push
